# When PEP621 is fully implemented move setup.cfg data here
# see https://setuptools.pypa.io/en/latest/history.html for progress

[build-system]
requires = [
    "cmake>=3.25.0,<4.0",
    "packaging",
    "gitpython",
    "setuptools>=42",
    "wheel"
]
# specify setuptools as packaging tool - setup.cfg contains config
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 99

[tool.flake8]
max-line-length = 99

[tool.isort]
# make it compatible with black
profile = "black"

[tool.cibuildwheel]
build = "cp311-* cp312-* cp313-* cp314-*"
test-command = "python {project}/test/run_doctest.py"
build-verbosity = 2
archs = "auto64"
skip = "cp2* pp*"
# test-skip = "*"

#PEP440TYPE is used to insert a qualifier in the version name
# It must be one of:
# "a" - alpha release
# "b" - beta release
# "rc" - release candidate + N or NN
# "" - final release (no build number)
# If PEP440TYPE = "a" or "b" the resulting name is "version" + [PEP440TYPE + "build_number"] 
#    -   where build number is calculated from commit count
# If PEP440TYPE = "" or "rcN" the resulting name is "version" + [PEP440TYPE]

[tool.cibuildwheel.windows]
build = "cp311-win_amd64 cp312-win_amd64 cp313-win_amd64 cp314-win_amd64"
#build = "cp313-win_amd64"
before-all = [
    "{project}\\.ci\\cleanwheelhouse.bat"
]
before-build = [
#    "python -m pip uninstall pip setuptools",
#    "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
#    "python get-pip.py",
    "{project}\\.ci\\cleanprevbuild.bat",
    "where python",
]

[tool.cibuildwheel.windows.environment]
CONAN_USER_HOME="$(cmd /c 'echo %cd%')"
PEP440TYPE="a"
FULL_VERSION="1.3.0.b1"


[tool.cibuildwheel.linux]
# These are passed into the docker
# environment = {CONAN_USER_HOME="$(pwd)", PEP440TYPE="a", FULL_VERSION="1.3.0.b1", CIBW_DEBUG_KEEP_CONTAINER=true, HDILib_channel="python"}
manylinux-x86_64-image = "manylinux_2_28"
build = "cp311-manylinux_x86_64 cp312-manylinux_x86_64 cp313-manylinux_x86_64 cp314-manylinux_x86_64"

# The following runs in the Linux docker environment
before-build = [
    "chmod +x {project}/.ci/cleanprevbuild.sh",
    "{project}/.ci/cleanprevbuild.sh",
    "dnf install -y lz4-devel libXrandr-devel libXinerama-devel libXcursor-devel libXi-devel wget",
    "cd ~ && mkdir ./vulkan && cd ./vulkan/ && wget https://sdk.lunarg.com/sdk/download/1.4.341.0/linux/vulkansdk-linux-x86_64-1.4.341.0.tar.xz",
    "cd ~/vulkan && tar xf vulkansdk-linux-x86_64-1.4.341.0.tar.xz",
    "source ~/vulkan/1.4.341.0/setup-env.sh && cd ~",
    "which python",]

before-test = [
    # "cp -r /project /host/home/bvanlew/tmp"
]
repair-wheel-command = [
    "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp/cibwlibsdir",
    "echo 'Lib path for repair $LD_LIBRARY_PATH'",
    "auditwheel show {wheel}",
    "auditwheel repair --plat manylinux_2_28_x86_64 -w {dest_dir} {wheel}"
]
test-command = "export CI=TRUE && python {project}/test/run_doctest.py"

[tool.cibuildwheel.linux.environment]
CONAN_USER_HOME = "$(pwd)"
PEP440TYPE = "a"
FULL_VERSION = "1.3.0.b1"
CIBW_DEBUG_KEEP_CONTAINER = true
HDILib_channel = "python"
Vulkan_SDK = "$HOME/vulkan/1.4.341.0/x86_64"



[tool.cibuildwheel.macos]
build-verbosity=3
build = ["cp311-*", "cp312-*", "cp313-*", "cp314-*"]
archs = ["arm64"]

before-all = [
    "HOMEBREW_NO_AUTO_UPDATE=1 brew install libomp && brew link --overwrite libomp && brew install vulkan-loader",
    "if [ -d \"./wheelhouse\" ]; then rm -Rf ./wheelhouse; fi",
    "mkdir ./wheelhouse"
]
before-build = [
#    "chmod +x {project}/.ci/cleanprevbuild.sh",
#    "{project}/.ci/cleanprevbuild.sh",
    "which python",
]
repair-wheel-command = [
    "export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$TMPDIR/cibwlibsdir",
    "echo 'Lib path for repair $DYLD_LIBRARY_PATH'",
    "delocate-listdeps {wheel} && delocate-wheel --require-archs arm64 -w {dest_dir} {wheel}"
]
test-command = "export CI=TRUE && python {project}/test/run_doctest.py"

[tool.cibuildwheel.macos.environment]
MACOSX_DEPLOYMENT_TARGET = "14.5"
CONAN_USER_HOME="$(pwd)"
PEP440TYPE="a"
FULL_VERSION="1.3.0.b1"
CMAKE_APPLE_SILICON_PROCESSOR="arm64"
