Version 1.3.0
-----------------
Supports python 3.9, 3.10, 3.11, 3.12, 3.13 on Windows, Ubuntu (using manylinux_2_28) and Macos (restricted to arm64).

Changelog 1.3.0
~~~~~~~~~~~~~~~
- Using the latest `HDI Library <http://github.com/biovault/HDILib>`_ 
  v1.2.10 supporting the additional Annoy knn method.

- The demos at |Demos_github_url| have been updated to include more exact requirements
  specification and have been updated for the newer matplotlib and PyQt6 apis. See :ref:`Demo list`

