[project]
name = "nptsnedemos"
version = "2.0.0a4"
description = "Demonstration scripts for nptsne"
dependencies = [
  "nptsne==2.0.0a4",
  "PyQt6==6.9.0",
  "matplotlib==3.10.1",
  "scipy==1.15.2",
  "numpy==2.2.4",
  "pandas==2.2.3",
  "Pillow==11.1.0",
  "notebook==7.5.5",
  "networkx==3.4.2",
  "python-louvain==0.16",
  "pywin32; sys_platform == 'win32'",
  "umap-learn==0.5.11",
  "zenodo-get==3.0.0"
]
requires-python = ">=3.11"

[tool.uv]
package = true
# This forces uv to install the current project (the demos) into the venv
# so that "import nptsne_demos" works.

#[dependency-groups]
#dev = [
#    { include-group = "nptsne_demos" }
#]

[tool.uv.workspace]
members = []

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple"
explicit = true


[project.scripts]
BasicHSNEDemo = "nptsnedemos.BasicHSNEDemo.hsnedemo:main"
ExtendedHSNEDemo = "nptsnedemos.ExtendedHSNEDemo.hsnedemo:main"
HSNELouvainDemo = "nptsnedemos.HSNELouvainDemo.testhsnelouvain:main"
SimpleTsne = "nptsnedemos.SimpleTsne.test:main"
ExtendedTsne = "nptsnedemos.ExtendedTsne.testtextureextended:main"
DocTest = "nptsnedemos.DocTest.run_doctest:main"
JupyterNotebookDemo = "nptsnedemos.TSNEJupyterNotebook.run_tsne_notebook:open_notebook"
GetDemoData = "nptsnedemos.GetDemoData.getdata:main"

[tool.uv.sources]
# This forces uv to look for 'nptsne' on TestPyPI 
# instead of failing when it's not on the main PyPI
nptsne = { index = "testpypi" }
nptsnedemos = { path = ".", editable = true }

[tool.setuptools]
package-dir = {"" = "src"}
packages = [
  "nptsnedemos", 
  "nptsnedemos.SimpleTsne",
  "nptsnedemos.BasicHSNEDemo",
  "nptsnedemos.HSNELouvainDemo"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

