[project]
name = "nptsnedemos"
version = "2.0.0rc1"
description = "Demonstration scripts for nptsne"
dependencies = [
  "nptsne==2.0.0rc1",
  "PyQt6==6.9.0",
  "matplotlib>=3.10.5",
  "scipy>=1.16.1",
  "numpy==2.2.4",
  "pandas==2.2.3",
  "Pillow>=12.0.0",
  "notebook==7.5.5",
  "networkx==3.4.2",
  "python-louvain==0.16",
  "pywin32; sys_platform == 'win32'",
  "umap-learn==0.5.11",
  "zenodo-get==3.0.0"
]
requires-python = ">=3.11, <3.14"

[project.scripts]
BasicHSNEDemo = "nptsnedemos.BasicHSNEDemo.hsnedemo:main"
ExtendedHSNEDemo = "nptsnedemos.ExtendedHSNEDemo.hsnedemo:main"
HSNELouvainDemo = "nptsnedemos.HSNELouvainDemo.testhsnelouvain:main"
SimpleTsne = "nptsnedemos.SimpleTsne.test:main"
ExtendedTsne = "nptsnedemos.ExtendedTsne.testtextureextended:main"
DocTest = "nptsnedemos.DocTest.run_doctest:main"
JupyterNotebookDemo = "nptsnedemos.TSNEJupyterNotebook.run_tsne_notebook:open_notebook"
GetDemoData = "nptsnedemos.GetDemoData.getdata:main"
DistanceMatrix = "nptsnedemos.DistanceMatrixDemo.test_dist:main"

[tool.uv]
package = true
# This forces uv to install the current project (the demos) into the venv
# so that "import nptsne_demos" works.

#[dependency-groups]
#dev = [
#    { include-group = "nptsne_demos" }
#]

[tool.uv.workspace]
members = []


[tool.uv.sources]
# Search internaal indexed for development purposes
nptsne = { index = "testpypi" }
#nptsne = { index = "wheelhouse" }
nptsnedemos = { path = ".", editable = true }


[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple"
explicit = true

# Set the correct path in the url to work with a local wheel
[[tool.uv.index]]
name = "wheelhouse"
url = "file:///D:/TempProj/nptsne/wheelhouse"
format = "flat"
explicit = true

[tool.setuptools]
package-dir = {"" = "src"}
packages = [
  "nptsnedemos", 
  "nptsnedemos.SimpleTsne",
  "nptsnedemos.BasicHSNEDemo",
  "nptsnedemos.HSNELouvainDemo",
  "nptsnedemos.DistanceMatrixDemo"
]

# 
[tool.create_demo_zip]
base = "./"
include = [
  "src/nptsnedemos",
  "data",
  "DEMOS_README.txt",
  "GETTING_MNIST.txt",
  "pyproject.toml",
  "uv.lock"
]


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "mypy>=1.19.1",
]

