name: Build

on: [push, pull_request, workflow_dispatch]

env:
  # Set READTHEDOCS to
  #   - "true" if this version is to be loaded to ReadTheDocs
  #   - "false" otherwise
  READTHEDOCS: "true"
  # PEP440TYPE is is used to qualify the version number
  # Set PEP440TYPE to
  #   - "a" if an alpha release
  #   - "b" if a beta release
  #   - "rc" if a release candidate
  #   - "" for the final release
  # Se python PEP 440 for more details on this convention
  PEP440TYPE: "a"

jobs:
  # Job to buildwheels on all platforms
  build_wheels:
    name: Build wheels on ${{ matrix.job-name}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - job-name: "Linux"
            os: "ubuntu-20.04"

          # - job-name: "macOS"
          #   os: "macos-10.15"
          #   xcode-version: "10.3"

          # - job-name: "Windows"
          #   os: "windows-2019"

    outputs:
      nptsneversion: ${{ steps.version.outputs.version }}

    steps:
      # see https://github.com/travis-ci/travis-ci/issues/6069#issuecomment-266546552
      # and https://stackoverflow.com/a/53409848/584201
      # A full checkout allows the git derived build number to work working (based on git log and rev-list)
      - name: Checkout the source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      # Used to host cibuildwheel
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"

      - name: Install cibuildwheel
        uses: pypa/cibuildwheel@v2.2.2

      # cibuildwheel settings are mostly in the pyproject.toml file

      # Test the cibuildwheel action
      # cibuildwheel derives platform automatically on CI
      # Local run use --platform windows/linx/macos
      - name: Build wheels all platforms
        uses: pypa/cibuildwheel@v2.2.2

      # get the branchname - needed for version derivation
      - uses: nelonoel/branch-name@v1.0.1
      - run: echo ${BRANCH_NAME}

      - id: version
        if: matrix.os == 'ubuntu-20.04'
        run: |
          pip install GitPython
          echo call setup for version
          python setup.py --version
          echo store version
          export VERSION=$(python setup.py --version)
          echo "::set-output name=version::$VERSION"

      # Temporary storage of job results
      # In later steps are collected and uploaded to (Test)PyPI
      # The default upload name is artifact but a name can be supplied
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          retention-days: 1
          if-no-files-found: error

  # TODO Add job to build sdist
  # Job to upload all artifacts after wheel & sdist build
  # Steps:
  #   1) Download artifacts from temp store
  #   2) Upload to either :
  #      a) - TestPyPI if no release tag
  #      b) - PyPI if release tag
  #   3) If the upload succeeds trigger either :
  #      a) - TestReadTheDocs if no release tag
  #      b) - ReadTheDocs if release tag

  upload_all_artifacts:
    name: Upload artifacts to pyPI or TestPyPI
    if: env.READTHEDOCS == "true"
    needs: [build_wheels]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.build_wheels.outputs.nptsneversion }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: Checkout the source
        uses: actions/checkout@v2

      - name: ReadTheDocs must have a tag - set it here
        if: env.READTHEDOCS == "true"
        run: |
          git tag $VERSION

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Publish wheels to PyPI
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN_SECRET  }}
      - name: readthedocs_pypi
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo T.B.D.

      - name: Publish wheels to TestPyPI
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_TOKEN_SECRET  }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish to ReadTheDocs
        run: |
          echo use nptsne:$VERSION for ReadTheDocs
          echo Check version $VERSION is on pypi or testpypi
          pip install requests

      - name: Verify wheel upload
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          import os
          import requests
          r=requests.get(f'https://test.pypi.org/project/nptsne/{os.environ["VERSION"]}')
          exit(0) if r.status_code==200 else exit(1)
        shell: python

      - name: Post to ReadTheDocs
        run: |
          curl -X POST -H "Authorization: Token ${{ secrets.READTHEDOCS_TOKEN  }}" -H "Content-Type: application/json" -d '{"active": true, "hidden": false}' "https://readthedocs.org/api/v3/projects/nptsne/versions/${VERSION}/builds/"
